### ISSUE TITLE
pecl missing from 7.0-dev build

### ISSUE THREAD

**Issue by bicatu** [liip/build-entropy-php#15]
Hi, I've installed the 7.0 and I've noticed that when I try to use pecl it complains : 

Could not open input file: /usr/local/php5/lib/php/peclcmd.php

If I switch to 5.6.8 (for example) I can execute normally

ls -lsa /usr/local/php5-5.6.8-20150417-141945/lib/php/peclcmd.php 
4 -rw-r--r-- 1 root wheel 1022 Apr 17 08:19 /usr/local/php5-5.6.8-20150417-141945/lib/php/peclcmd.php

On php7 such thing.

ls -lsa /usr/local/php5-7.0.0-dev-20150417-194402/lib/php/
total 4
0 drwxr-xr-x   4 root wheel  136 Apr 22 21:18 .
0 drwxr-xr-x 197 root wheel 6698 Apr 22 21:18 ..
4 lrwxr-xr-x   1 root wheel   25 Apr 22 21:18 build -> /usr/local/php5/lib/build
0 drwxr-xr-x   3 root wheel  102 Apr 22 21:18 extensions

**Comment by chregu** [comment]
I disabled pear back then (this commit https://github.com/liip/build-entropy-php/commit/3eced1e350fa86f44396a059c21b584be8c4ee19 ) when I did the first port of PHP 7, maybe that got pecl disabeld as well. I can try later, if this is fixed in PHP 7
