### ISSUE TITLE
Add 10.11 El Capitan branches

### ISSUE THREAD

**Issue by Cretezy** [liip/build-entropy-php#16]
Pretty simple. The 10.10 versions should work in the meantime.

**Comment by chregu** [comment]
Do we actually need them, if the 10.10 builds just work?
(we don't have branches for 10.7 and 10.9 for example, as 10.6 and 10.8 just runs on those)

**Comment by Cretezy** [comment]
Alright, that's what I thought. I did https://github.com/liip/php-osx/pull/154 too.
